// Plik konfiguracyjny (Baza danych) EduBox AI
// Jeśli dodajesz nową aplikację, po prostu dopisz tu nowy obiekt!

window.EduBoxData = {
    RECOMMENDATIONS: [
        { name: 'Chmurka AI', url: 'https://chmurka.ai/', icon: '☁️', desc: 'Obrazy, wideo, muzyka w jednym miejscu.' },
        { name: 'ChatGPT', url: 'https://chat.openai.com/', icon: '🤖', desc: 'Najpotężniejszy model językowy.' },
        { name: 'Suno AI', url: 'https://suno.com/', icon: '🎵', desc: 'Twórz piosenki na zajęcia z AI.' }
    ],

    APPS: [
        // --- TERAPIA I SPE ---
        { title: 'EduKasia PRO', desc: 'Asystent przedszkolny. Porady SOS, mówik AAC, dziennik sukcesów i bajki!', url: 'edukasia.html', badge: 'DLA KASI ❤️', badgeColor: 'bg-rose-600', icon: 'ph-heart', color: 'text-rose-500', category: 'terapia', tags: ['przedszkole', 'bajki', 'aac'] },
        { title: 'Asystent Dostosowań', desc: 'Dobiera formy dostosowania wymagań pod zadaną diagnozę ucznia.', url: 'edudostosowania.html', icon: 'ph-shield-check', color: 'text-blue-500', category: 'terapia', tags: ['dostosowania', 'wymagania', 'diagnoza'] , verified2026: true },
        { title: 'EduDialog AI (Tłumacz)', desc: 'Przetłumaczy Twój nerwowy tekst na dyplomatyczną wiadomość dla rodzica.', url: 'eduterapia.html', icon: 'ph-chats', color: 'text-violet-500', category: 'terapia', tags: ['rodzice', 'wiadomość', 'dyplomacja'] },
        { title: 'EduTerapia PRO (TUS)', desc: 'Kompletne plany zajęć Treningu Umiejętności Społecznych.', url: 'eduterapia.html', badge: 'TERAPIA', badgeColor: 'bg-pink-600', icon: 'ph-users-three', color: 'text-pink-500', category: 'terapia', tags: ['tus', 'terapia', 'społeczne'] },
        { title: 'Generator Historyjek 3D', desc: 'Układa spersonalizowaną historyjkę dla dziecka i rysuje ilustracje.', url: 'eduterapia.html', badge: 'AI GRAFIKA', badgeColor: 'bg-pink-600', icon: 'ph-video-camera', color: 'text-pink-500', category: 'terapia', tags: ['bajki', 'historyjki', 'czytanie'] },
        { title: 'EduWizualizator (AAC)', desc: 'Dzieli trudną czynność na kroki z piktogramami (Najpierw-Potem).', url: 'eduwizualizator.html', badge: 'AAC', badgeColor: 'bg-yellow-500 text-yellow-950', icon: 'ph-stack', color: 'text-yellow-500', category: 'terapia', tags: ['aac', 'autism', 'wizualizacja'] },
        { title: 'Tablice Najpierw-Potem', desc: 'Przeciwdziałanie oporowi. Tablica "Zadanie - Nagroda" gotowa do druku.', url: 'eduwizualizator.html', icon: 'ph-layout', color: 'text-orange-500', category: 'terapia', tags: ['aac', 'nagroda', 'motywacja'] },
        { title: 'EduChunk AI', desc: 'Dla uczniów z ADHD/Dysleksją. Dzieli trudny tekst na czytelne fiszki.', url: 'chunking.html', badge: 'INKLUZJA', badgeColor: 'bg-teal-600', icon: 'ph-brain', color: 'text-teal-500', category: 'terapia', tags: ['dysleksja', 'adhd', 'fiszki', 'chunking'] },
        { title: 'Asystent Sensoryki (SI)', desc: 'Baza tanich, szybkich zabaw sensorycznych celujących w układ proprioceptywny.', url: 'eduterapia.html', icon: 'ph-hand-pointing', color: 'text-fuchsia-500', category: 'terapia', tags: ['si', 'sensoryka', 'zabawy'] },
        { title: "EduBajka PRO (Ilustrowana)", desc: "Generator bajek terapeutycznych. Podaj problem ucznia (np. strach, złość), a AI stworzy 4-stronicową, pięknie ilustrowaną książeczkę do druku.", url: "edubajka.html", badge: "HIT / SPE", badgeColor: "bg-purple-600", icon: "ph-book-bookmark", color: "text-purple-500", category: "terapia", tags: ["bajki", "terapia", "książki", "emocje"] },
        { title: 'EduSymbol AI', desc: 'Twórz grafiki do ksiąg komunikacyjnych w gotowej siatce do wydruku.', url: 'edusymbol.html', icon: 'ph-squares-four', color: 'text-fuchsia-500', category: 'terapia', tags: ['symbole', 'aac', 'karty'] },
        { title: 'EduSOS PRO', desc: 'Trudne zachowanie ucznia? AI podpowie metody i psychologiczne rady.', url: 'edusos.html', icon: 'ph-lifebuoy', color: 'text-fuchsia-500', category: 'terapia', tags: ['sos', 'pomoc', 'trudne zachowania'] },
        { title: 'EduPiktogram', desc: 'Kreator Planów Dnia AAC, gotowy do wydruku.', url: 'edupiktogram.html', icon: 'ph-image-square', color: 'text-emerald-500', category: 'terapia', tags: ['plan dnia', 'aac', 'piktogramy'] },

        // --- BIUROKRACJA I DOKUMENTY ---
        { title: 'EduOddech - Chwila dla Nauczyciela', desc: 'Krótkie, sprawdzone ćwiczenia oddechowe i relaksacyjne. 2, 5 albo 10 minut dla siebie między lekcjami.', url: 'eduoddech.html', badge: 'NOWOŚĆ', badgeColor: 'bg-teal-600', icon: 'ph-heart', color: 'text-teal-500', category: 'terapia', tags: ['dobrostan', 'stres', 'oddech', 'nauczyciel'] },
        { title: 'Asystent Pedagoga (IPET)', desc: 'Tworzy kompletne IPET-y i WOPFU w oparciu o prawo oświatowe.', url: 'asystent-pedagoga.html', badge: 'SPE', badgeColor: 'bg-rose-600', icon: 'ph-file-text', color: 'text-rose-500', category: 'biurokracja', tags: ['ipet', 'wopfu', 'specjalna'] , verified2026: true },
        { title: 'Asystent Wdrożenia Reformy 2026', desc: 'Sprawdź dokładnie, co zmienia się w Twojej klasie od 1 września 2026 r. i jak się przygotować.', url: 'edureforma.html', badge: 'NOWOŚĆ', badgeColor: 'bg-teal-600', icon: 'ph-compass', color: 'text-teal-500', category: 'biurokracja', tags: ['reforma', 'kompas jutra', 'podstawa programowa'] , verified2026: true },
        { title: 'Kreator Awansu AI', desc: 'Automatyczne sprawozdania i "Ocena Dorobku Zawodowego".', url: 'awans.html', badge: 'AWANS', badgeColor: 'bg-blue-600', icon: 'ph-briefcase', color: 'text-blue-500', category: 'biurokracja', tags: ['awans', 'dorobek', 'sprawozdanie'] , verified2026: true },
        { title: 'EduAwans PRO MAX', desc: 'Edytor sprawozdań z AI. Generuj i drukuj oficjalne dokumenty awansowe w PDF.', url: 'eduawans.html', badge: 'AWANS MAX', badgeColor: 'bg-blue-600', icon: 'ph-briefcase', color: 'text-blue-500', category: 'biurokracja', tags: ['awans', 'pdf', 'dokumenty'] , verified2026: true },
        { title: 'EduWycieczka Organizator', desc: 'Wyliczy zrzutkę, napisze na Librusa i stworzy gotowe zgody RODO do druku.', url: 'eduwycieczka.html', badge: 'NOWOŚĆ', badgeColor: 'bg-emerald-600', icon: 'ph-map-trifold', color: 'text-emerald-500', category: 'biurokracja', tags: ['wycieczka', 'rodo', 'librus'] },
        { title: 'EduPrawo AI', desc: 'Interpretacja Prawa Oświatowego i generowanie gotowych wniosków urzędowych.', url: 'eduprawo.html', badge: 'PRAWO MEN', badgeColor: 'bg-red-600', icon: 'ph-scales', color: 'text-red-500', category: 'biurokracja', tags: ['prawo', 'ustawa', 'wniosek'] , verified2026: true },
        { title: 'EduBiurokrata AI', desc: 'Sformalizowane protokoły zebrań z rodzicami oraz zgody.', url: 'edubiurokrata.html', icon: 'ph-file-doc', color: 'text-blue-500', category: 'biurokracja', tags: ['zebrania', 'protokół', 'zgody'] },
        { title: 'Kreator Opinii (PPP)', desc: 'Zamienia brudnopis w oficjalną Opinię do Poradni z żargonem PPP.', url: 'edudialog.html', icon: 'ph-signature', color: 'text-rose-500', category: 'biurokracja', tags: ['ppp', 'opinia', 'poradnia'] },
        { title: 'EduSprawozdawca PRO', desc: 'AI analizuje notatki i pliki PDF, by wygenerować sprawozdanie roczne.', url: 'edusprawozdania.html', badge: 'NOWOŚĆ', badgeColor: 'bg-emerald-500', icon: 'ph-presentation-chart', color: 'text-emerald-500', category: 'biurokracja', tags: ['sprawozdanie', 'półrocze', 'rok'] },
        { title: 'Notatki Służbowe', desc: 'Zmienia emocjonalny opis zdarzenia w chłodną, urzędową notatkę.', url: 'edubiurokrata.html', icon: 'ph-clipboard-text', color: 'text-slate-400', category: 'biurokracja', tags: ['notatka', 'dziennik', 'służbowa'] },
        { title: 'EduOcena AI', desc: 'Kreator Ocen Opisowych. Wyklikaj umiejętności na świadectwo!', url: 'eduocena.html', badge: 'OCENY', badgeColor: 'bg-violet-600', icon: 'ph-user-check', color: 'text-violet-500', category: 'biurokracja', tags: ['ocena', 'opisowa', 'świadectwo'] },
        { title: 'EduKorektor AI (NAZU)', desc: 'Sprawdza tekst ucznia, podając 2 jego mocne strony (zamiast jedynek).', url: 'edukorektor.html', icon: 'ph-target', color: 'text-violet-500', category: 'biurokracja', tags: ['korektor', 'sprawdzanie', 'ocenianie'] },
        { title: 'EduWpisy PRO (Dziennik)', desc: 'Koniec wymyślania! Generuje ultra-profesjonalne, urzędowe wpisy do dziennika (Librus/Vulcan) z uwzględnieniem zapisów o dzieciach ze SPE.', url: 'eduwpisy.html', badge: 'HIT MEN', badgeColor: 'bg-indigo-600', icon: 'ph-pencil-line', color: 'text-indigo-500', category: 'biurokracja', tags: ['dziennik', 'librus', 'vulcan', 'spe', 'wpisy'] },
        { title: "EduPDF Edytor", desc: "Korektor i wypełniacz plików PDF. Zamazuj błędy, dodawaj własny tekst i twórz puste strony bez psucia oryginalnego układu.", url: "edupdf.html", badge: "NOWOŚĆ", badgeColor: "bg-blue-600", icon: "ph-file-pdf", color: "text-blue-500", category: "biurokracja", tags: ["pdf", "edytor", "dokumenty", "korektor", "wypełniacz"] },
        { title: "EduRaport AI", desc: "Automatyczny asystent sprawozdań. Zamienia luźne notatki z wycieczek, projektów i mentoringu w profesjonalne, wielostronicowe ewaluacje gotowe dla dyrekcji.",url: "eduraport.html",icon: "ph-check-square-offset",color: "text-emerald-500",category: "biurokracja",tags: ["sprawozdanie", "ewaluacja", "wycieczka", "mentor", "awans", "dokumenty"],badge: "NOWOŚĆ",badgeColor: "bg-red-500"},
        { title: "EduNotariusz AI", desc: "Twoja urzędowa tarcza. Przekształca chaotyczne notatki z trudnych rozmów z rodzicami w profesjonalne, obiektywne dokumenty i protokoły.", url: "edunotariusz.html",icon: "ph-scales",color: "text-amber-500",category: "biurokracja",tags: ["prawo", "notatka służbowa", "protokół", "trudne sytuacje", "rodzice", "ochrona", "urzędowe"],badge: "NOWOŚĆ",badgeColor: "bg-red-500"},

        // --- ZAJĘCIA I GRY ---
        { title: 'Scenariusz AI PRO', desc: 'Tworzy 45-minutowe konspekty ze skryptem dialogowym dla nauczyciela.', url: 'eduscenariusz.html', badge: 'HIT! PRO', badgeColor: 'bg-emerald-600', icon: 'ph-book-open', color: 'text-emerald-500', category: 'zajecia', tags: ['konspekt', 'scenariusz', 'lekcja'] },
        { title: 'Edukacja 2025 AI', desc: 'Debaty i symulacje pod nową Edukację Obywatelską i Zdrowotną.', url: 'edukacja2025.html', badge: 'NOWOŚĆ', badgeColor: 'bg-emerald-600', icon: 'ph-sparkle', color: 'text-emerald-500', category: 'zajecia', tags: ['obywatelska', 'zdrowotna', 'debaty'] , verified2026: true },
        { title: 'EduZadania AI', desc: 'Generuje matematyczne zadania tekstowe z ulubionymi postaciami dzieci.', url: 'eduzadania.html', badge: 'GRYWALIZACJA', badgeColor: 'bg-sky-500', icon: 'ph-calculator', color: 'text-sky-500', category: 'zajecia', tags: ['matematyka', 'zadania', 'grywalizacja'] },
        { title: 'EduSprawdzian Maker', desc: 'Zrobi test (Grupa A i B) na podstawie wklejonej notatki z lekcji.', url: 'edusprawdzian.html', icon: 'ph-exam', color: 'text-emerald-500', category: 'zajecia', tags: ['sprawdzian', 'test', 'kartkówka'] },
        { title: "EduKalendarz PRO MAX", desc: "Baza Świąt Nietypowych. Generuje gotowe zajęcia 'Zero-Prep' (bez przygotowania) i łączy Cię z innymi narzędziami EduBoxa.", url: "edukalendarz.html", badge: "NOWOŚĆ", badgeColor: "bg-violet-600", icon: "ph-calendar-star", color: "text-violet-500", category: "zajecia", tags: ["kalendarz", "święta nietypowe", "scenariusz", "zajęcia"] },
        { title: 'EduZastępstwo 999', desc: 'Nagłe zastępstwo? Baza kreatywnych gier słownych bez ksera (Zero-Prep).', url: 'eduzastepstwo.html', icon: 'ph-warning-circle', color: 'text-emerald-500', category: 'zajecia', tags: ['zastępstwo', 'gry', 'słowne'] },
        { title: 'EduTimer PRO', desc: 'Wizualny stoper i harmonogram etapów lekcji na tablicę interaktywną.', url: 'edustoper.html', badge: 'NOWOŚĆ', badgeColor: 'bg-amber-500 text-amber-950', icon: 'ph-hourglass', color: 'text-amber-500', category: 'zajecia', tags: ['stoper', 'czas', 'harmonogram'] },
        { title: 'EduTIK Inspirator PRO', desc: 'Podpowiada gry i za pomocą AI generuje do nich gotowe zagadki i hasła.', url: 'edutik.html', badge: 'GENERATOR', badgeColor: 'bg-fuchsia-600', icon: 'ph-lightbulb', color: 'text-fuchsia-500', category: 'zajecia', tags: ['tik', 'gry', 'quizy'] },
        { title: 'Łowca Fake Newsów', desc: 'Rozwija krytyczne myślenie. AI tworzy fałszywy artykuł do zdemaskowania.', url: 'edukacja2025.html', icon: 'ph-detective', color: 'text-emerald-500', category: 'zajecia', tags: ['fake news', 'dziennikarstwo', 'myślenie'] , verified2026: true },
        { title: 'EduPrezentacja PRO', desc: 'Generator prezentacji z eksportem do PPTX. AI układa plan i grafiki do slajdów.', url: 'eduprezentacja.html', badge: 'NOWOŚĆ', badgeColor: 'bg-blue-600', icon: 'ph-projector-screen-chart', color: 'text-blue-500', category: 'zajecia', tags: ['prezentacja', 'slajdy', 'powerpoint'] },
        { title: 'EduKomiks AI', desc: 'Wymyśla opowieść z morałem, rysuje kadry i nakłada komiksowe dymki.', url: 'edukomiks.html', badge: 'NOWOŚĆ', badgeColor: 'bg-yellow-400 text-black', icon: 'ph-chats-teardrop', color: 'text-yellow-500', category: 'zajecia', tags: ['komiks', 'obrazki', 'kreatywne'] },
        { title: 'EduMotywator AI', desc: 'Koniec zadań do domu! Generuje wciągające Karty Wyjścia (Exit Tickets).', url: 'edumotywator.html', badge: 'GRYWALIZACJA', badgeColor: 'bg-fuchsia-600', icon: 'ph-ticket', color: 'text-fuchsia-500', category: 'zajecia', tags: ['karty wyjścia', 'ewaluacja'] },
        { title: 'EduGrupy (Koło Fortuny)', desc: 'Animowane Koło Fortuny do losowania uczniów i dzielenia na równe grupy.', url: 'edugrupy.html', badge: 'GRYWALIZACJA', badgeColor: 'bg-pink-600', icon: 'ph-spinner-gap', color: 'text-pink-500', category: 'zajecia', tags: ['losowanie', 'koło fortuny', 'grupy'] },
        { title: 'EduFiszki i Memory AI', desc: 'Wyciąga słowa kluczowe z tekstu i układa dwustronne fiszki PDF gotowe do druku.', url: 'edufiszki.html', badge: 'HIT!', badgeColor: 'bg-fuchsia-600', icon: 'ph-cards', color: 'text-fuchsia-500', category: 'zajecia', tags: ['fiszki', 'memory', 'nauka'] },
        { title: 'EduGry (Ja Mam)', desc: 'Gra, która ożywi klasę. System łączy podane słowa w zamkniętą pętlę kart.', url: 'edugry.html', badge: 'ROZRYWKA', badgeColor: 'bg-rose-600', icon: 'ph-game-controller', color: 'text-rose-500', category: 'zajecia', tags: ['ja mam', 'gry'] },
        { title: 'Kreator BINGO', desc: 'Wpisz słówka z lekcji, a system wygeneruje 30 unikalnych plansz BINGO!', url: 'edugry.html', icon: 'ph-grid-four', color: 'text-indigo-500', category: 'zajecia', tags: ['bingo', 'plansze', 'gry'] },
        { title: 'EduBystrzak AI', desc: 'Wybierz temat. Dostaniesz gotowe karty Dobble (6 kółek na A4) do gry z klasą!', url: 'edubystrzak.html', badge: 'HIT!', badgeColor: 'bg-fuchsia-600', icon: 'ph-lightning', color: 'text-fuchsia-500', category: 'zajecia', tags: ['dobble', 'spostrzegawczość', 'karty'] },
        { title: 'EduEscape PRO', desc: 'Generator fabularnych Escape Roomów. Twórz angażujące karty zagadek i szyfry.', url: 'eduescape.html', icon: 'ph-key', color: 'text-violet-500', category: 'zajecia', tags: ['escape room', 'zagadki', 'szyfry'] },
        { title: 'EduBoxPro Studio', desc: 'Zaawansowany kombajn. Generuje scenariusze TikTok/Reels edukacyjnych.', url: 'studio.html', badge: 'STUDIO', badgeColor: 'bg-fuchsia-600', icon: 'ph-film-strip', color: 'text-fuchsia-500', category: 'zajecia', tags: ['tiktok', 'reels', 'wideo'] },
        { title: 'EduWakacje PRO', desc: 'Zero-Prep dla wychowawców. Generuje plany półkolonii, gry terenowe i ratunkowe zabawy (SOS). Wspiera grupy SPE.', url: 'eduwakacje.html', badge: 'WAKACJE', badgeColor: 'bg-amber-500 text-amber-950', icon: 'ph-sun', color: 'text-amber-500', category: 'zajecia', tags: ['wakacje', 'kolonie', 'półkolonie', 'gry', 'zabawy', 'lato', 'spe'] },
        { title: "EduWystrój AI",desc: "Kreator całych pakietów dekoracyjnych. Generuje gazetki, kodeksy, dekoracje na drzwi i szyldy w perfekcyjnym formacie wektorowym do druku.",url: "edudekorator.html",icon: "ph-scissors",color: "text-emerald-600",category: "grafika",tags: ["dekoracje", "gazetki", "wystrój", "kodeks", "drzwi", "plakaty", "przedszkole"],badge: "HIT",badgeColor: "bg-red-500"},

        { title: 'EduKatalog (Generator Ofert)', desc: 'Automatycznie tworzy profesjonalną ofertę zajęć dodatkowych na bazie Twoich aplikacji EduBox.', url: 'edukatalog.html', badge: 'NOWOŚĆ', badgeColor: 'bg-emerald-600', icon: 'ph-briefcase', color: 'text-emerald-500', category: 'biurokracja', tags: ['oferta', 'katalog', 'marketing'] },

        // --- GRAFIKA I KREATYWNE ---
        { title: 'EduGenerator PRO', desc: 'Cudowne dyplomy dla klasy i ozdobne girlandy ze zintegrowanym wycinaniem tła.', url: 'edugenerator.html', badge: 'PREMIUM', badgeColor: 'bg-indigo-600', icon: 'ph-certificate', color: 'text-indigo-500', category: 'grafika', tags: ['dyplomy', 'girlandy'] },
        { title: 'EduDyplomy AI', desc: 'Generator rymowanych dyplomów "z przymrużeniem oka" na koniec roku.', url: 'edudyplomy.html', badge: 'KONIEC ROKU', badgeColor: 'bg-rose-500', icon: 'ph-medal', color: 'text-rose-500', category: 'grafika', tags: ['dyplomy', 'wierszyki', 'zakończenie'] },
        { title: 'Magic Color AI', desc: 'Inteligentny rysownik. Wpisz dowolny pomysł, a AI narysuje go dla Twoich dzieci.', url: 'magiccolor.html', icon: 'ph-magic-wand', color: 'text-pink-500', category: 'grafika', tags: ['kolorowanki', 'rysunki', 'grafika'] },
        { title: 'EduPlakat AI', desc: 'Generator pięknych grafik i plakatów. Opisz scenę, a AI stworzy czystą ilustrację.', url: 'eduplakat.html', badge: 'NOWOŚĆ', badgeColor: 'bg-purple-600', icon: 'ph-image', color: 'text-purple-500', category: 'grafika', tags: ['plakat', 'ilustracja', 'grafika'] },
        { title: 'EduStudio AI', desc: 'Zaawansowane studio graficzne. Wybieraj oświetlenie, kadry i proporcje suwakami.', url: 'edustudio.html', badge: 'PRO', badgeColor: 'bg-indigo-600', icon: 'ph-sliders', color: 'text-indigo-500', category: 'grafika', tags: ['studio', 'grafika', 'kreator'] },
        { title: 'EduGazetka AI', desc: 'Generator wystroju klasy. Gigantyczne litery i 4 gotowe plakaty informacyjne (A4).', url: 'edugazetka.html', badge: 'HIT!', badgeColor: 'bg-teal-600', icon: 'ph-newspaper', color: 'text-teal-500', category: 'grafika', tags: ['gazetka', 'wystrój', 'plakaty'] },
        { title: 'EduBoxPro MagicLetters', desc: 'Profesjonalny generator girland ze wsparciem AI. Własne tła, kształty i tekstury.', url: 'magicletters.html', badge: 'NOWOŚĆ', badgeColor: 'bg-purple-600', icon: 'ph-text-aa', color: 'text-purple-500', category: 'grafika', tags: ['girlandy', 'litery', 'napisy'] },
        { title: 'Kreator Ikon PRO', desc: 'Zrób porządek na pulpicie. Konwertuje grafiki na profesjonalne pliki Windows .ICO.', url: 'https://kreator-ikon.vercel.app/', icon: 'ph-app-window', color: 'text-slate-400', category: 'grafika', tags: ['ikony', 'ico', 'pulpit'] },
        { title: "EduMalarz AI",desc: "Twój profesjonalny asystent graficzny. Generuje medale, ramki, zaproszenia i naklejki w formatach gotowych do wydruku.",url: "edumalarz.html",icon: "ph-palette",color: "text-pink-500",category: "grafika",tags: ["grafika", "medale", "zaproszenia", "naklejki", "rysunki", "dekoracje", "przedszkole"], badge: "PREMIUM",badgeColor: "bg-purple-600"},
        {  title: 'EduDetox AI', desc: 'Humorystyczny asystent wakacyjny. Wygeneruje dla Ciebie przezabawny autoresponder na Librusa i wystawi certyfikat za przetrwanie roku!',  url: 'edudetox.html',  badge: 'VIRAL', badgeColor: 'bg-teal-500 text-slate-900', icon: 'ph-plant', color: 'text-teal-400', category: 'zajecia', tags: ['wakacje', 'urlop', 'relaks', 'śmieszne', 'humor', 'detox'] }
    ]
};
