'use strict';

// Jawna lista publikacji. Nowy plik HTML NIE trafia do Google automatycznie.
// Aby opublikować stronę, właściciel musi świadomie dopisać ją do publicPages.
module.exports = {
  baseUrl: 'https://eduboxpro.pl',
  defaultImage: '/okladka.jpg',
  reportDirectory: 'seo-reports',
  publicPages: [
    { path: 'index.html', url: '/', changefreq: 'daily', priority: '1.0' },
    { path: 'blog.html', changefreq: 'weekly', priority: '0.8' },
    { path: 'co-nowego.html', changefreq: 'weekly', priority: '0.6' },
    { path: 'centrum-lekcje.html', changefreq: 'weekly', priority: '0.8', seoTitle: 'Narzędzia do lekcji i zajęć | EduBox AI', seoDescription: 'Scenariusze, zadania, quizy i pomoce dydaktyczne EduBox AI. Wybierz konkretne narzędzie i przygotuj lekcję szybciej.' },
    { path: 'centrum-dokumenty.html', changefreq: 'weekly', priority: '0.8', seoTitle: 'Dokumenty i biurokracja szkolna | EduBox AI', seoDescription: 'Narzędzia EduBox AI do opinii, IPET, WOPFU, sprawozdań i szkolnych dokumentów. Znajdź właściwy generator bez szukania po nazwach.' },
    { path: 'centrum-spe.html', changefreq: 'weekly', priority: '0.8', seoTitle: 'Terapia, AAC i wsparcie SPE | EduBox AI', seoDescription: 'Narzędzia EduBox AI do dostosowań, AAC, TUS, terapii i wsparcia uczniów ze specjalnymi potrzebami edukacyjnymi.' },
    { path: 'centrum-grafika.html', changefreq: 'weekly', priority: '0.8', seoTitle: 'Grafiki i materiały dla szkoły | EduBox AI', seoDescription: 'Dyplomy, plakaty, prezentacje, obrazy i wideo dla nauczycieli. Otwórz centrum materiałów graficznych EduBox AI.' },
    { path: 'standardy-ochrony-maloletnich.html', changefreq: 'monthly', priority: '0.7', ogType: 'article' },
    { path: 'polityka-prywatnosci.html', changefreq: 'monthly', priority: '0.5', ogType: 'article' },
    { path: 'dlaczego-pro.html', changefreq: 'monthly', priority: '0.7' },
    { path: 'asystent-pedagoga.html' },
    { path: 'awans.html' },
    { path: 'chunking.html' },
    { path: 'eduawans.html' },
    { path: 'edubajka.html' },
    { path: 'edubiurokrata.html' },
    { path: 'edubystrzak.html' },
    { path: 'edudekorator.html' },
    { path: 'edudetox.html' },
    { path: 'edudialog.html' },
    { path: 'edudostosowania.html' },
    { path: 'edudyplom.html' },
    { path: 'edudyplomy.html' },
    { path: 'eduescape.html' },
    { path: 'edufiszki.html' },
    { path: 'edugazetka.html' },
    { path: 'edugenerator.html' },
    { path: 'edugrupy.html' },
    { path: 'edugry.html' },
    { path: 'edukacja2025.html' },
    { path: 'edukalendarz.html' },
    { path: 'edukasia.html' },
    {
      path: 'edukatalog.html',
      seoDescription: 'EduKatalog tworzy profesjonalną ofertę zajęć dodatkowych na podstawie aktualnej listy aplikacji EduBox AI.',
    },
    { path: 'edukomiks.html' },
    { path: 'edukorektor.html' },
    { path: 'edulekcja360.html', priority: '0.9' },
    { path: 'edumalarz.html' },
    { path: 'edumotywator.html' },
    { path: 'edunotariusz.html' },
    { path: 'eduocena.html' },
    { path: 'eduoddech.html' },
    { path: 'edupdf.html' },
    { path: 'edupiktogram.html' },
    { path: 'eduplakat.html' },
    { path: 'edupodsumowanie.html' },
    { path: 'eduprawo.html' },
    { path: 'eduprezentacja.html' },
    { path: 'eduraport.html' },
    { path: 'edureforma.html' },
    { path: 'edurymy.html' },
    { path: 'eduscenariusz.html' },
    { path: 'edusos.html' },
    { path: 'edusprawdzian.html' },
    { path: 'edusprawozdania.html' },
    { path: 'edustoper.html' },
    { path: 'edustudio.html' },
    { path: 'edusymbol.html' },
    { path: 'eduterapia.html' },
    { path: 'edutik.html' },
    { path: 'eduwakacje.html' },
    { path: 'eduwizualizator.html' },
    { path: 'eduwpisy.html' },
    { path: 'eduwycieczka.html' },
    { path: 'eduzadania.html' },
    { path: 'eduzastepstwo.html' },
    { path: 'magiccolor.html' },
    { path: 'magicletters.html' },
    { path: 'studio.html' },
  ],
  excludedPages: [
    { path: 'aniawideo.html', reason: 'Prywatny Generator Wideo Ani (Basic Auth)' },
    { path: 'ewamarketing.html', reason: 'Prywatny Generator Influencerki (Basic Auth)' },
    { path: 'kreator-menu.html', reason: 'Wewnętrzny Kreator Wpisów do Menu' },
    { path: 'redaktor-ogloszen.html', reason: 'Wewnętrzny Redaktor Ogłoszeń' },
    { path: 'redaktorbloga.html', reason: 'Wewnętrzny Redaktor Bloga' },
    { path: 'panel-jakosci.html', reason: 'Prywatny panel jakości automatyzacji Make' },
    { path: 'panel-link.html', reason: 'Wewnętrzny generator linków kampanii (UTM)' },
    { path: 'panel-analytics.html', reason: 'Prywatny panel statystyk społecznościowych (Basic Auth)' },
    { path: 'menu.html', reason: 'Fragment nawigacji, nie samodzielna strona' },
    { path: 'teczka.html', reason: 'Prywatna lokalna Teczka użytkownika, bez treści publicznej' },
    { path: 'test-edubiurokrata.html', reason: 'Strona testowa' },
    { path: 'api/index.html', reason: 'Techniczna kopia strony głównej w katalogu API' },
  ],
  robotsDisallow: [
    '/api/',
    '/aniawideo.html',
    '/ewamarketing.html',
    '/kreator-menu.html',
    '/redaktor-ogloszen.html',
    '/redaktorbloga.html',
    '/panel-jakosci.html',
    '/panel-link.html',
    '/panel-analytics.html',
    '/teczka.html',
    '/test-edubiurokrata.html',
  ],
  blog: {
    page: 'blog.html',
    dataFile: 'blog-posts.js',
    changefreq: 'monthly',
    priority: '0.7',
  },
};
